In [ ]:
import pandas as pd

# analise exploratória

dataset = pd.read_csv("alugueis_brasil.csv")

dataset.columns = [
    "cidade",
    "area",
    "quartos",
    "banheiros",
    "vagas_estacionamento",
    "andar",
    "aceita_animais",
    "mobiliado",
    "valor_condominio",
    "valor_do_aluguel",
    "IPTU",
    "seguro_incendio",
    "valor_total",
]
describe_dataset = dataset.describe().map('{:,.2f}'.format)
describe_dataset


media_aluguel_por_cidade = (
    dataset.groupby("cidade")["valor_do_aluguel"]
    .mean()
    .reset_index()
)



media_aluguel_por_cidade.columns = ["cidade", "valor_do_aluguel"]
media_aluguel_por_cidade['valor_do_aluguel'] = media_aluguel_por_cidade['valor_do_aluguel'].map('R$ {:,.2f}'.format)
display(media_aluguel_por_cidade)

quantidade_total_imoveis= dataset.groupby('cidade').size().reset_index()
quantidade_total_imoveis.columns = [['cidade', 'quantidade']]
display(quantidade_total_imoveis)

dataset_cidade = dataset[['cidade', 'aceita_animais']].groupby('cidade').count().reset_index()

dataset_cidade

           cidade valor_do_aluguel
0  Belo Horizonte      R$ 3,664.13
1        Campinas      R$ 2,364.29
2    Porto Alegre      R$ 2,337.70
3  Rio de Janeiro      R$ 3,232.90
4       São Paulo      R$ 4,652.79

           cidade quantidade
0  Belo Horizonte       1258
1        Campinas        853
2    Porto Alegre       1193
3  Rio de Janeiro       1501
4       São Paulo       5887

           cidade  aceita_animais
0  Belo Horizonte            1258
1        Campinas             853
2    Porto Alegre            1193
3  Rio de Janeiro            1501
4       São Paulo            5887